# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{typhoeus}
  s.version = "0.0.22"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Dix"]
  s.date = %q{2009-08-26}
  s.email = %q{paul@pauldix.net}
  s.extensions = ["ext/typhoeus/extconf.rb"]
  s.files = [
    ".gitignore",
     "README.textile",
     "Rakefile",
     "VERSION",
     "benchmarks/profile.rb",
     "benchmarks/vs_nethttp.rb",
     "examples/twitter.rb",
     "ext/typhoeus/.gitignore",
     "ext/typhoeus/extconf.rb",
     "ext/typhoeus/native.c",
     "ext/typhoeus/native.h",
     "ext/typhoeus/typhoeus_easy.c",
     "ext/typhoeus/typhoeus_easy.h",
     "ext/typhoeus/typhoeus_multi.c",
     "ext/typhoeus/typhoeus_multi.h",
     "lib/typhoeus.rb",
     "lib/typhoeus/.gitignore",
     "lib/typhoeus/easy.rb",
     "lib/typhoeus/filter.rb",
     "lib/typhoeus/multi.rb",
     "lib/typhoeus/remote.rb",
     "lib/typhoeus/remote_method.rb",
     "lib/typhoeus/remote_proxy_object.rb",
     "lib/typhoeus/response.rb",
     "lib/typhoeus/service.rb",
     "profilers/valgrind.rb",
     "spec/fixtures/result_set.xml",
     "spec/servers/app.rb",
     "spec/servers/delay_fixture_server.rb",
     "spec/servers/method_server.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/typhoeus/easy_spec.rb",
     "spec/typhoeus/filter_spec.rb",
     "spec/typhoeus/multi_spec.rb",
     "spec/typhoeus/remote_method_spec.rb",
     "spec/typhoeus/remote_proxy_object_spec.rb",
     "spec/typhoeus/remote_spec.rb",
     "spec/typhoeus/response_spec.rb",
     "typhoeus.gemspec",
     "typhoeus.gemspec",
     "typhoeus.gemspec"
  ]
  s.homepage = %q{http://github.com/pauldix/typhoeus}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = [["lib", "ext"]]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A library for interacting with web services (and building SOAs) at blinding speed.}
  s.test_files = [
    "spec/servers/app.rb",
     "spec/servers/delay_fixture_server.rb",
     "spec/servers/method_server.rb",
     "spec/spec_helper.rb",
     "spec/typhoeus/easy_spec.rb",
     "spec/typhoeus/filter_spec.rb",
     "spec/typhoeus/multi_spec.rb",
     "spec/typhoeus/remote_method_spec.rb",
     "spec/typhoeus/remote_proxy_object_spec.rb",
     "spec/typhoeus/remote_spec.rb",
     "spec/typhoeus/response_spec.rb",
     "examples/twitter.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
